# This is dummy data for local, not for production obviously
from datetime import date
VENDORS = [
    {
        "id": 1,
        "first_name": "Adam",
        "last_name": "Park",
        "email": "vendedor1@email.com",
        "password": "vendedor1",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 2,
        "first_name": "Eric",
        "last_name": "Cartman",
        "email": "eric_cartman@email.com",
        "password": "vendedor2",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 3,
        "first_name": "Stan",
        "last_name": "Marsh",
        "email": "stan_marsh@email.com",
        "password": "vendedor3",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 4,
        "first_name": "Kyle",
        "last_name": "Broflovski",
        "email": "kyle_br@email.com",
        "password": "vendedor4",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 5,
        "first_name": "Kenny",
        "last_name": "McCormick",
        "email": "kennyMC@email.com",
        "password": "vendedor5",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 6,
        "first_name": "Butters",
        "last_name": "Stotch",
        "email": "butters_sto@email.com",
        "password": "vendedor6",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
    {
        "id": 7,
        "first_name": "Wendy",
        "last_name": "Testaburger",
        "email": "wendy@email.com",
        "password": "vendedor7",
        "birthday": date(1990, 1, 1),
        "privilege": 2,
    },
]
